version: "3.7"

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker
      dockerfile: Nginx.Dockerfile
    ports:
      - 80:80
    links:
      - fpm
    volumes:
        - ./:/var/www/datasub-api
  fpm:
    container_name: fpm
    build:
      context: ./docker
      dockerfile: Fpm.Dockerfile
    volumes:
      - ./:/var/www/datasub-api
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=${DB_DATABASE}
